# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fe9eec640c1a95628b0164768c4f461e78edfffefbd0e694ef602437b52827a4fc0c7e79d232e5d815f4b9fa8d02120a215f57a0e62a2080efa2d67b650fdc50

test:
  secret_key_base: 20776a7b90decde502b3fafb8ea2a52b32d9bd68e9c9233766a5f87a92a18ee2dc14e309c2e26d5e40578d6a1001a6bdfaecddd6e4e14477804e7662fb6f19f0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
